[package]
name = "hirschberg"
description = "Generic implementation of Hirschberg's algorithm in Rust"
version = "0.1.0"
edition = "2021"
authors = ["Nick Senger <dev@nsenger.com>"]
readme = "README.md"
repository = "https://github.com/nicksenger/hirschberg/"
license = "MIT"

[dependencies]
